### ISSUE TITLE
Enhancement: Can we re-factor script_run further?

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/ReQUIAM#119]
**Summary**
`script_run` has grown dramatically that it's too excessive. A review of it is needed to identify areas where we can refactor common actions/operations. For example, for `portal` and `quota` could this be simplified into a functional action.

**Objectives**
A noticeable reduction in `script_run` so it's more manageable.

**Proposal**
A review is needed first before we decide on the best path forward.

*Testing notes*
Full execution of `script_run` with `--sync`

*Additional notes*
This should definitely occur after #117 

**Implemented in**: TBD

**Comment by yhan818** [comment]
I am not sure if any effort shall be spent on this issue. 
Reasons: 
-- "portal" and "quota" parameters are used for different purpose. see Patron management documentation 2.2.1. 
-- "sync" parameter is necessary to keep for testing (dry run is very useful to identify the issues but do not do any real changes). 
-- Documentation is recently updated so that any system admin/software developer knows how to run the script for IAM. 
-- I did not see any benefits for changing with the script. 

So I suggest to close this issue.

**Comment by zoidy** [comment]
While I agree that it would be beneficial to refactor the code to make it cleaner, I also agree that the code is working reliably and any gains to refactoring would be minimal when there are bigger fish to fry.
