### ISSUE TITLE
Enhancement: Capturing API failures to avoid script dying entirely

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/ReQUIAM#126]
**Summary**
`script_run` often runs OK but there are times when it fails. These occurs most often with Grouper API calls, most likely when the Grouper server becomes unresponsive. The issue is that this results in the script dying and requires us to re-run the script. This does not help if we run these scripts as part of our CI build as failures may not be due to the codebase but the service.

**Objectives**
`script_run` without any issues and re-runs when API calls fail.

**Proposal**
Have a way to capture this failure and then re-running the `requests` call with a time delay is the simplest solution. There should be a configuration settings of the number of runs and the delay time.

*Testing notes*

Note that with Grouper v2.5 testing, I recommend holding off on this unless a clean solution is easily available.

*Additional notes*
This [SO thread](https://stackoverflow.com/questions/16511337/correct-way-to-try-except-using-python-requests-module) could be useful in ways to capture these failures, but still unclear what errors are provided in such cases.

**Implemented in**: TBD

**Comment by yhan818** [comment]
After watching script-run a few months after Grouper v2.5 upgrade, it still happened a few times (less than 5% time). Majority of time script-run just did not complete the last updates. In other words, only one or two units are being affected when not 100% completed. In these months, I have watched closely the next day or 2 if the script_run is not completed. The next scheduled run (next day) is almost 100% successful. The only time it did not run is due to the total number of updates > 1000 (which was max to update in configuration file). 

Since the consequence is very very minor. Also the next day run is successful. It seems me if it is not necessary to have an automatic solution, because a daily check happens anyhow.  I consider this issue as a balance of efforts and gains /risk and return. 

Two options:
1. Re-run "script_run" when an error is caught by writing an additional script. Also make the additional script as a cron job running in a different time (e.g. 5 hours later )
2. Simply closed the issue. Just manually run "script_run" if necessary.
