### ISSUE TITLE
Verbose logging when performing changes

### ISSUE THREAD

**Issue by zoidy** [UAL-RE/ReQUIAM#39]
When performing portal and quota updates, please add the option for additional verbosity which not only includes summary information about what will change, but include the actual changes as well. This increases our capacity to troubleshoot issues should they arise.

For example, current log info when performing a portal update on the tech_eng portal (similarly for quota updates)
```
11:33:07 -     INFO: Working on Technology & Engineering (tech_eng) portal
<snip>
11:33:11 -     INFO:  EDS size 1250
11:33:11 -     INFO:  Grouper size 1
11:33:11 -     INFO: ldap and grouper have 0 members in common
11:33:11 -     INFO: synchronization will drop 1 entries from grouper group
11:33:11 -     INFO: synchronization will add 1250 entries to grouper group
11:33:11 -     INFO: dry run, not performing synchronization
```

Desired logging info
```
11:33:07 -     INFO: Working on Technology & Engineering (tech_eng) portal
<snip>
11:33:11 -     INFO:  EDS size 1250
11:33:11 -     INFO:  Grouper size 1
11:33:11 -     INFO: ldap and grouper have 0 members in common
11:33:11 -     INFO: synchronization will drop 1 entries from grouper group
11:33:11 -     DEBUG: Dropping (name : employeeprimarydept )
                     Jane R. Smith : 0121
11:33:11 -     INFO: synchronization will add 1250 entries to grouper group
11:33:11 -     DEBUG: Adding (name : employeeprimarydept )
                     Mary A. Researcher : 2308
                     Mary B. Researcher : 2308
                     Mary C. Researcher : 2308
<snip>
11:33:11 -     INFO: dry run, not performing synchronization
```

**Comment by astrochun** [comment]
One thing worth considering is a `--verbose` flag to specify the level of details.  With large groups, it becomes difficult to identify other problems as the logs will consists of just messages about individual users.  Take the case of the quota.  That alone might have lists on the order of 10,000 or more for base quota levels. We already know those settings for each classification.  It might be worthwhile to perform this verboseness with manual override cases only.

Getting information about each user add/delete is difficult in the current software as we do not include their names.  We only look at their UA ID (`uaid`). This is because Grouper `requests` depend on this unique ID and not other EDS attributes.  With set logic, it's easy to handle unique `uaid` to remove redundancy (not sure if an EDS query would return two other possible case), but not names and org codes.  That would require use of list, which will complicate the code implementation.  The advantage of only working with `uaid` is also the anonymization.

**Comment by zoidy** [comment]
The verbose flag would be fine

**Comment by astrochun** [comment]
By default, the verbosity is provided if changes are < 20. However, the information provided will not include full name and organization code as that requires are more complex LDAP API call with response time taking longer.

Verbosity is disabled in CI with `ci` flag.
